[LM-10817] Changes analytics flow
LikeMindsCommunity/likeminds-chat-reactnative pull request #19
Opened 2024-02-20 19:11 UTC by jaixchaudhary

**Description**
- Analytics flow
- Removed alert from custom callback

2024-02-20 19:21 UTC, ishaan1607 approved these changes

2024-02-21 03:38 UTC, arnavr15 approved these changes

2024-02-21 03:38 UTC, arnavr15 commented on likeminds-chat-reactnative-integration/ChatSX/utils/analyticsUtils.ts
> +    const voiveNoteCount =
it should be `voiceNoteCount`

2024-02-23 18:10 UTC, ishaan1607 requested changes

2024-02-23 18:10 UTC, ishaan1607 commented on likeminds-chat-reactnative-integration/ChatSX/utils/analyticsUtils.ts
> +    const voiveNoteCount =
Rename to `voiceNoteCount`

2024-02-23 18:23 UTC, merged